FROM microsoft/aspnetcore-build
WORKDIR /app
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN bower install --allow-root
RUN dotnet ef database update --environment Production
RUN dotnet publish --output /out/ --configuration Release
ENTRYPOINT ["dotnet", "SitePeinture.dll"]